### ISSUE TITLE
Manual plugin install?

### ISSUE THREAD

**Issue by Evidlo** [return-of-modding/ReturnOfModding#21]
I appreciate the simple instructions for manual installation of ReturnOfModding without mod manager.  Can plugins be similarly installed manually?

Specifically it's not clear whether I should be making the `ReturnOfModding/plugins/[plugin_name]` directory myself or where `ReturnOfModding` is supposed to go relative to `Risk of Rain Returns.exe`.

**Comment by xiaoxiao921** [comment]
https://github.com/xiaoxiao921/ReturnOfModdingBase?tab=readme-ov-file#folder-convention

**Comment by Evidlo** [comment]
I've read that README, but it doesn't explain where the `ReturnOfModding/` folder actually goes relative to the RoR executable.

I've tried to guess what it should look like, but the mods don't seem to be working:

```
├── musicTitle.ogg
├── options.ini
├── ReturnOfModding
│   └── plugins
│       └── foobar-enableconsole
│           ├── main.lua
│           └── manifest.json
├── Risk of Rain Returns.exe
├── RoRRWinExt.dll
├── steam_api64.dll
...
├── version.dll
```
