### ISSUE TITLE
feat(dynamic_prov_trials): Manipulate, create, activate providence trials using lua code at runtime

### ISSUE THREAD

**Issue by AndreLouisIssa** [return-of-modding/ReturnOfModding#7]
Capabilities for treating providence trials as first-class objects inside of the lua API:
- Load/Save the content of an existing providence trial (regarding files and within an in-game structure)
- Manipulate the data of a providence trial using regular lua code (likely as nested tables)
- Activate a providence trial from lua at any time, including custom ones that have not been saved.

**Comment by xiaoxiao921** [comment]
Out of scope
