### ISSUE TITLE
feat(imgui_hotkeys_keybinds): ImGui hotkey support + custom keybind callbacks/checks

### ISSUE THREAD

**Issue by AndreLouisIssa** [return-of-modding/ReturnOfModding#8]
- To allow mod UI to accept custom hotkeys so they don't have to be on-screen buttons
- To allow for setting and checking and reacting to keybinds even outside of ImGui
- To separate ImGui input from game input and vice versa

**Comment by xiaoxiao921** [comment]
can't recall the commit but pretty sure the ImgGui table support it now
